# This is a basic workflow to help you get started with Actions

name: Test_with_Jest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: npm_install
        run: npm install
      - name: run_test_code
        run: npm test
      - name : if_fail
        uses: actions/github-script@0.2.0
        with:
            github-token: ${{secrets.TOKEN}}
            script : |
              const ref = "${{github.ref}}"
              const pull_number = Number(ref.split("/")[2])
              console.log(pull_number, ref.split("/"), github.ref)
              await github.pulls.createReview({
                ...context.repo,
                pull_number,
                body : "테스트코드를 다시 확인해주세요. ",
                event : "REQUEST_CHANGES"
              })
              await github.pulls.update({
                ...context.repo,
                pull_number,
                state: "closed"
              })
        if: failure()
